### ISSUE TITLE
what is the shape of pred_keypoints_mpii.mat matrix?

### ISSUE THREAD

**Issue by yellowcheng** [anibali/eval-mpii-pose#11]
hi, i want to know what is the matrix shape of pred_keypoints_mpii.mat when you submit to mpii.

**Comment by anibali** [comment]
It's supposed to be the same as the annotation file, but with the predicted coordinates filled in. See http://human-pose.mpi-inf.mpg.de/#evaluation

**Comment by yellowcheng** [comment]
thanks
