### ISSUE TITLE
What‘s the keypoints order in preds(2958x16x2)?

### ISSUE THREAD

**Issue by Sierkinhane** [anibali/eval-mpii-pose#12]

**Comment by Sierkinhane** [comment]
Must be a Matlab (.mat) or HDF5 (.h5) file
Must have one field, preds, which is the joint predictions tensor
Tensor size must be [2 x 16 x n] or [n x 16 x 2]

 It's the same with mpii annotation? like these (0 - r ankle, 1 - r knee, 2 - r hip, 3 - l hip, 4 - l knee, 5 - l ankle, 6 - pelvis, 7 - thorax, 8 - upper neck, 9 - head top, 10 - r wrist, 11 - r elbow, 12 - r shoulder, 13 - l shoulder, 14 - l elbow, 15 - l wrist)

**Comment by anibali** [comment]
Yes, the joints should be stored in the same order as the MPII annotation.

**Comment by Sierkinhane** [comment]
Thanks!
