### ISSUE TITLE
pchk

### ISSUE THREAD

**Issue by henbucuoshanghai** [anibali/eval-mpii-pose#15]
你好  pckh什么意思呢？？？？比如DNN得到预测的一堆xy坐标   和ground truth的xy直接 怎样计算呢？？

help

**Comment by anibali** [comment]
Hi, I don't understand Chinese but from what I can tell using Google Translate this seems like a pretty general/fundamental question (not specific to this project). I would recommend asking it somewhere else so that the communication is clearer.
