### ISSUE TITLE
Showed the"Assertion failed."when I specified the predictions in evalMPII.m

### ISSUE THREAD

**Issue by PCRKTY** [anibali/eval-mpii-pose#17]
**Scripts**
Loads predictions from Matlab or HDF5 files and compares them with ground truth labels to calculate accuracy metrics (eg PCKh). You will want to edit getExpParamsNew.m to add new sets of predictions, and evalMPII.m to specify which predictions to include and which subset (train/val) to use.
****
I have edited  `getExpParamsNew.m` to add the new prediction such as 
```
case 6
    p.name = 'XXX';
    p.predFilename = 'preds/reference/XXX.mat';
```
And I edited the `evalMPII.m`
```
PRED_IDS = [1, 2, 5, 6];
```
But it shows the error
Error using evalMPII (line 82)
Assertion failed.

**Comment by anibali** [comment]
It means that you do not have the correct number of predictions in your prediction file. You must match the number of predictions in `train.h5` or `valid.h5` (depending on the subset).

**Comment by PCRKTY** [comment]
I tried to evaluate it on the test.h5, rather not valid.h5 cus my .mat file also generated by test-set.
Does this means that your script can't evaluate on test-set?
Should I use `prepareTestResults.m` to convert my test-set predictions to  `pred_keypoints_mpii.mat ` and submit it to the official email of MPII?
Thank you.

**Comment by anibali** [comment]
> Does this means that your script can't evaluate on test-set?

Correct, since the test set ground truth annotations are not public.

> Should I use prepareTestResults.m to convert my test-set predictions to pred_keypoints_mpii.mat and submit it to the official email of MPII?

Yes.

**Comment by PCRKTY** [comment]
Thank you very much. ^_^
