### ISSUE TITLE
assert error

### ISSUE THREAD

**Issue by 738654805** [anibali/eval-mpii-pose#3]
prepareTestResults (line 42)
assert fail

**Comment by anibali** [comment]
That assert is there to (partially) validate the input. If it triggers, it means that the number of examples in the predictions doesn't match the annotation file.

**Comment by 738654805** [comment]
but i just use the file (newell.h5) you provide.

**Comment by anibali** [comment]
Alright, I'll look into it when I get a chance.

**Comment by 738654805** [comment]
Thanks for your reply.I do not know how to prepare test set results for submission to MPII for evaluation.Your code helps a lot,the evaluation script on page(http://human-pose.mpi-inf.mpg.de/#evaluation) is hard to understand.Thanks for you help,appreciate.

**Comment by anibali** [comment]
I figured out what you were trying to do, and here is why it won't work:

The predictions in `preds/reference` are for the **validation set**, and are intended for use with `evalMPII.m`. The `prepareTestResults.m` script is for preparing **test set** predictions for submission. It won't work for validation set predictions.

**Comment by anibali** [comment]
I've clarified this point in https://github.com/anibali/eval-mpii-pose/commit/2ae99137b02b2d1b3d221e8a042ecfc5206b424b so that others aren't confused by it in the future.
