### ISSUE TITLE
Has anyone verified the correctness of prepareTestResults.

### ISSUE THREAD

**Issue by abeardear** [anibali/eval-mpii-pose#7]
I have generate a (11731,16,2) sized test_preds.h5, and i want to transform it to official mat file. Have you did it before that submit a predict result to official mail and get a feedback result. @anibali hope for your help~

**Comment by anibali** [comment]
Yes, I have used this code to generate a Matlab format file which I submitted for evaluation by the dataset organisers. The accuracy they gave was in line with what I expected, so I am reasonably confident that the conversion code works OK.
