### ISSUE TITLE
Converting .mat to .csv file

### ISSUE THREAD

**Issue by sebo361** [anibali/eval-mpii-pose#9]
Hi @anibali and thanks for your work!

Can you share the script for converting the `mpii_human_pose_v1_u12_1.mat` to the `.h5` files? Do you know if there is code for converting the `mpii_human_pose_v1_u12_1.mat` to a `.csv` file? 
Im asking because I want to train my model explicity on one category of movement `(act_id)` within MPII dataset. So im thinking of converting the dataset to .csv file i order to delete the not desired data manually. Then i want to bring it in [this .csv format](https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Reaching-Mackenzie-2018-08-30/labeled-data/reachingvideo1/CollectedData_Mackenzie.csv) or [this .h5 format](https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Reaching-Mackenzie-2018-08-30/labeled-data/reachingvideo1/CollectedData_Mackenzie.h5). What do you think about my idea? Any hints for solving that?

**Comment by anibali** [comment]
As I mention in the readme, the .h5 annotation files are from https://github.com/anewell/pose-hg-train/tree/master/data/mpii/annot. I didn't generate those myself. If you want to do your own manipulation of the .mat annotations, you might find this https://github.com/anibali/eval-mpii-pose/issues/5#issuecomment-409395046 helpful.

**Comment by sebo361** [comment]
Thanks a lot!
